version: 2

jobs:
  build:
    docker:
      - image: alpine:edge
    steps:
      - checkout
      - run: apk add git clang cmake build-base ninja autoconf automake libtool texinfo gettext-dev libexecinfo-dev
      - run: git submodule update --init --recursive
      - run:
          name: make
          command: |
            mkdir build && \
            cd build && \
            CC=clang CXX=clang++ cmake -G Ninja .. && \
            ninja -j2
      - store_artifacts:
          path: build/libfake-jni.so
      - store_artifacts:
          path: build/examples/examples
      - store_artifacts:
          path: build/tests/tests
      - store_artifacts:
          path: include/fake-jni/
  #example:
  #  docker:
  #   - image: alpine:edge
  #  steps:
  #   - run: ./build/examples/examples
  #test:
  #  docker:
  #   - image: alpine:edge
  #  steps:
  #   - run: ./build/tests/tests

workflows:
  version: 2
  build:
   jobs:
    - build
#    - test:
#        requires:
#         - build
#    - example:
#        requires:
#         - build
    - deploy:
        requires:
         - build
#         - example
#         - test
